### ISSUE TITLE
Use Child logger

### ISSUE THREAD

**Issue by J0las** [THI-Drone/common_package#11]
As you can see in this [commit](https://github.com/THI-Drone/fcc_bridge_package/pull/1/commits/a69c4f07ffe9cb8b1e2feaad4c2e799b5a390d21) one can use child loggers to group log messages.
This could then be used to better filter log messages in the telemetry output.
I suggest to at least use this approach for the CommonNode to allow one to filter out the heartbeat los but this might be of intereset for the other packages as well.
@J0hn-Lawrence das wäre vllt. auch für dich interessant, weil es den gesamten Logging ansatz betrifft.

**Comment by Philipp66904** [comment]
There are currently no resources available to fulfill your request.
Please try again later.

**Comment by J0las** [comment]
Das wontfix war dir dann wohl zu Mutig😅
Da erwarte ich aber einen POSIX konformen return code wir EBUSY sonst crashed mein message handler

**Comment by Philipp66904** [comment]
Ja, das `wontfix` klang so, als gäbe es einen Bug, der nicht gefixt wird...
